name: K6 Load Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (K6 & k6-reporter)
        run: |
          sudo apt update
          sudo apt install -y gnupg curl ca-certificates
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list > /dev/null
          sudo apt update
          sudo apt install -y k6
          wget https://github.com/szkiba/k6-reporter/releases/latest/download/k6-reporter-linux-amd64.zip
          unzip k6-reporter-linux-amd64.zip
          chmod +x k6-reporter
          sudo mv k6-reporter /usr/local/bin/

      - name: Run K6 Load Test
        run: |
          mkdir -p reports
          k6 run test.js --summary-export=result.json || true

      - name: Generate HTML Report
        run: |
          k6-reporter result.json reports/k6_report.html

      - name: Upload HTML Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: loadtest-html-report
          path: reports/k6_report.html

      - name: Send HTML Report via Email
        if: always()
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ secrets.EMAIL_RECEIVER }}
          subject: "📊 K6 Load Test Report"
          body: |
            Hello,

            Please find the attached HTML report for the recent K6 Load Test.

            Regards,  
            GitHub Actions 🤖
          attachments: reports/k6_report.html
