name: k6 Load Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y gnupg curl ca-certificates
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list > /dev/null
          sudo apt update
          sudo apt install -y k6

      - name: Run K6 Load Test
        run: |
          mkdir -p reports
          k6 run test.js --summary-export=reports/result.json || true

      - name: Convert JSON to HTML report
        if: always()
        run: |
          npm install -g k6-to-html
          k6-to-html reports/result.json -o reports/k6_report.html

      - name: Upload Report Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: k6-html-report
          path: reports/k6_report.html

      - name: Send HTML Report via Email
        if: always()
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ secrets.EMAIL_RECEIVER }}
          subject: "K6 Load Test Report"
          body: |
            Hello,

            Please find the attached HTML report for the recent K6 Load Test.

            Regards,  
            GitHub Actions
          attachments: reports/k6_report.html
          
