name: K6 Load Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install K6
        run: |
          sudo apt update
          sudo apt install -y gnupg curl ca-certificates unzip
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list > /dev/null
          sudo apt update
          sudo apt install -y k6

      - name: Run K6 test and export summary
        run: k6 run --summary-export=result.json test.js

      - name: Ensure clean output path
        run: |
          if [ -e reports/k6_report.html ]; then
            echo "Cleaning up existing k6_report.html (file or folder)..."
            rm -rf reports/k6_report.html
          fi

      - name: Generate HTML Report
        run: node generateReport.js

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: k6_html_report
          path: reports/k6_report.html

      - name: List report directory contents
        run: ls -l reports

      - name: Check report path before emailing
        run: |
         echo "Verifying report type..."
         file reports/k6_report.html
         ls -la reports/
         
      - name: Confirm report is a file
        run: file reports/k6_report.html

      - name: Send HTML Report via Email
        if: always()
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ secrets.EMAIL_RECEIVER }}
          subject: "K6 Load Test Report"
          body: |
            Hello,

            Please find the attached HTML report for the recent K6 Load Test.

            Regards,  
            GitHub Actions
          attachments: reports/k6_report.html

