name: k6 Load Test

on:
  push:
    branches: [main]
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y gnupg curl ca-certificates
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list > /dev/null
          sudo apt update
          sudo apt install -y k6

      - name: Run k6 test
        run: k6 run test.js

