name: k6 Load Test

on:
  push:
    branches: [main]
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y gnupg curl ca-certificates
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list > /dev/null
          sudo apt update
          sudo apt install -y k6

      - name: Run k6 test and generate HTML report
        run: |
          mkdir -p reports
          k6 run --summary-export=reports/summary.json test.js
          echo "<html><body><h2>K6 Load Test Summary</h2><pre>$(cat reports/summary.json)</pre></body></html>" > reports/k6_report.html

      - name: Send report via email
        uses: mattnotmitt/email@v1.2.0
        with:
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ secrets.EMAIL_RECEIVER }}
          subject: "K6 Load Test Report"
          body: |
            Hi,  
            Please find attached the latest K6 Load Test Report.
            
            Regards,  
            GitHub Actions
          attachments: reports/k6_report.html
          smtp-server: smtp.gmail.com
          smtp-port: 587
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

